'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

fib_list = [1, 2]
sums = 0

for i in range(2, 100000):
    new_num = fib_list[i - 1] + fib_list[i - 2]
    if new_num <= 4000000:
        fib_list.append(new_num)
    else:
        break

for i in range(len(fib_list)):
    if fib_list[i] & 1 == 0:
        sums += fib_list[i]

print(sums)
